[tools]
rust = "1.93"

[tasks."server"]
run = 'cargo run --bin server -- ${DATA_DIR:+--data "$DATA_DIR"}'

[tasks."convert"]
run = 'cargo run --bin convert -- ${DATA_DIR:+--data "$DATA_DIR"}'

[tasks."list"]
run = 'cargo run --bin list -- ${DATA_DIR:+--data "$DATA_DIR"}'
